### ISSUE TITLE
教程部分内容可能已过时，需修改

### ISSUE THREAD

**Issue by FurryRbl** [nakanomikuorg/arch-guide#106]
例如 plasma 设置语言部分
暂未发现更多

**Comment by Errant404** [comment]
臣复议，建议根据最新的[ArchWiki](https://wiki.archlinuxcn.org/wiki/安装指南) 全面地修订一次

**Comment by ice-kylin** [comment]
是的，但本人精力有限，特别是今明两年会比较忙，只能抽空维护文档，所以更多的需要靠大家一起维护 🤧

有空我会列一份 todo-list。

**Comment by wuhang2003** [comment]
大规模的修订重写要不考虑先开个分支慢慢整？
等完善得差不多了再扔回主分支

**Comment by FurryRbl** [comment]
> 大规模的修订重写要不考虑先开个分支慢慢整？ 等完善得差不多了再扔回主分支

其实本来就应该这样呀😂

**Comment by wuhang2003** [comment]
> > 大规模的修订重写要不考虑先开个分支慢慢整？ 等完善得差不多了再扔回主分支
> 
> 其实本来就应该这样呀joy

基操啊，还以为都是有啥改啥直接扔主分支的（

**Comment by dnslin** [comment]
开个 feature 进行迭代维护
