### ISSUE TITLE
文档不自动构建了

### ISSUE THREAD

**Issue by wuhang2003** [NakanoMikuOrg/arch-guide#111]
@ice-kylin 最近的几次提交 Travis CI 都没自动构建
查看了下提交记录，问题是在 724f20b283eddbe6901423d94493b67b079d455a 开始的，再查看 Travis CI 那边发现是免费额度用完了
要不考虑迁到 Actions 进行文档构建？

**Comment by ice-kylin** [comment]
在修了 QAQ
