### ISSUE TITLE
两个简明指南网站？

### ISSUE THREAD

**Issue by s-chance** [nakanomikuorg/arch-guide#136]
https://arch-linux.osrc.com/
https://arch.icekylin.online/
这两个网站都指向了这个仓库。不过第一个网站似乎有一段时间没有更新了，部分信息存在差异。这第一个网站和现在的仓库介绍里给出的第二个网站都还在维护吗？

**Comment by ice-kylin** [comment]
第一个域名的网站应该是其它人部署的，第二个域名的网站会在仓库发生修改后自动部署。
