### ISSUE TITLE
触摸板部分没有内容

### ISSUE THREAD

**Issue by zll600** [nakanomikuorg/arch-guide#141]
我发现触摸板这部分只有一个标题，我自己在装系统的时候是通过 KDE 下的 `Setting` -> `Input Devices` -> `TouchPad` 来设置的。官方 wiki 我没有找到图形化设置这部分。所以想请教一下这样设置是否可以。

![image](https://github.com/nakanomikuorg/arch-guide/assets/71714656/92e696ec-9059-49c8-b738-10f20e61a64a)

**Comment by wuhang2003** [comment]
在 [libinput](https://wiki.archlinuxcn.org/wiki/Libinput) 这呢（
