### ISSUE TITLE
为什么我的显卡与显示器里没有显示特效混合器

### ISSUE THREAD

**Issue by Suan-Nai6** [nakanomikuorg/arch-guide#142]
![image](https://github.com/nakanomikuorg/arch-guide/assets/77868531/b1f04385-3e2f-49e9-975e-e8692373af69)
![image](https://github.com/nakanomikuorg/arch-guide/assets/77868531/768a43f6-de4e-4e8d-bd60-155c3a374319)

**Comment by wuhang2003** [comment]
显示特效合成器就是（
文档中截图都是21/22年截的，有的已跟不上新版本 KDE 的变化了
