### ISSUE TITLE
美化terminal

### ISSUE THREAD

**Issue by 1754165401** [nakanomikuorg/arch-guide#147]
https://arch.icekylin.online/guide/advanced/beauty-3.html想请教一下这里怎么把konsole设置为半透明模糊这种感觉的，在网上找了很多教程都没有解决我的问题

**Comment by wuhang2003** [comment]
https://github.com/vinceliuice/Layan-kde

换个全局主题吧（
~~（虽然我也不知道为什么文档不整全 Layan~~

**Comment by Errant404** [comment]
应该是这个主题[BreezeBlurred](https://github.com/alex47/BreezeBlurred)，很可惜这个主题已经不维护了
