### ISSUE TITLE
有关初始安装部分的修补建议

### ISSUE THREAD

**Issue by w568w** [nakanomikuorg/arch-guide#151]
感谢作者的教程，引导我完成了第一次 Archlinux 安装。

不过在安装过程中，我发现教程中存在一些问题，希望查证：

1. 「archlinux 基础安装」一节中，介绍使用如下指令安装附加软件：

```sh
pacstrap /mnt dhcpcd networkmanager vim sudo zsh zsh-completions
```

实际上，根据 [网络配置](https://wiki.archlinuxcn.org/wiki/%E7%BD%91%E7%BB%9C%E9%85%8D%E7%BD%AE#%E7%BD%91%E7%BB%9C%E7%AE%A1%E7%90%86%E5%99%A8) 一节，这里的 `dhcpcd` 是「网络管理器」 `netctl` 使用的「DHCP 客户端」，而「网络管理器」 `networkmanager` 本身就内置了一个「DHCP 客户端」，因此无需再安装多余的 `dhcpcd`。另外实际上，Wiki 还明确指出：「不能同时运行两个 DHCP 客户端」。

2. 同一节中，介绍在安装阶段使用如下命令来探测其他操作系统：

```sh
pacman -S grub efibootmgr os-prober
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=ARCH
```

但在实际安装中，我发现无论是虚拟机（VirtualBox on Windows）还是实机（Lenovo Region 系列笔记本电脑），`os-prober` 都无法在安装环境下探测到任何其他操作系统（即便安装了 `ntfs-3g` 软件包），只有重启进入 Archlinux 后，才能探测到实际系统。我猜测这一问题与 `chroot` 环境有关，希望将这一点加入相关步骤的 Tips 中供其他读者了解。

3. 在较小的硬盘空间和部分 Windows 版本中，Windows 在安装时仅会划分约 128MB 空间给 EFI 系统分区，这[不足以让 Archlinux 正常安装](https://wiki.archlinuxcn.org/wiki/Arch_%2B_Windows_%E5%8F%8C%E7%B3%BB%E7%BB%9F#Windows_%E5%AE%89%E8%A3%85%E7%A8%8B%E5%BA%8F%E7%95%99%E4%B8%8B%E7%9A%84_EFI_%E7%B3%BB%E7%BB%9F%E5%88%86%E5%8C%BA%E8%BF%87%E4%BA%8E%E5%B0%8F)。**然而，「安装前的准备」一节对此并无提及，而「archlinux 基础安装」一节也直到「分区和格式化（使用 Btrfs 文件系统） 」部分才轻描淡写地说明「EFI 分区为 256MB」，对此现象没有任何说明，也没有为已经进行到这一步的读者提供解决问题的办法。** 鉴于这一现象较为普遍，可以在「准备」中强调 EFI 分区的大小要求，或者提供 [替代的解决方案](https://wiki.archlinuxcn.org/wiki/EFI_%E7%B3%BB%E7%BB%9F%E5%88%86%E5%8C%BA#%E5%85%B8%E5%9E%8B%E6%8C%82%E8%BD%BD%E7%82%B9)：

> [挂载](https://wiki.archlinuxcn.org/wiki/%E6%8C%82%E8%BD%BD) EFI 系统分区到 /efi， 然后再挂载一个 “拓展引导加载器分区”（XBOOTLDR）分区到 /boot。在以前创建的 ESP 太小而无法容纳多个引导加载程序以及内核但 ESP 又无法轻松调整大小时（例如在 Windows 之后将 Linux 安装到 [双引导（多引导）](https://wiki.archlinuxcn.org/wiki/Arch_%2B_Windows_%E5%8F%8C%E7%B3%BB%E7%BB%9F) 时），这可能非常有用。至少在 [systemd-boot#使用 XBOOTLDR 安装](https://wiki.archlinuxcn.org/wiki/Systemd-boot#Installation_using_XBOOTLDR) 时支持此方法。

**Comment by wuhang2003** [comment]
搁了个 PR 修了下你刚才讲的三点问题（
另外第二点问题你想的没错，[官方 Wiki](https://wiki.archlinuxcn.org/wiki/GRUB#%E6%8E%A2%E6%B5%8B%E5%85%B6%E4%BB%96%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F) 里边就有说：

> os-prober在chroot中可能无法正常运作。如果遇到这种情况，重启并引导进入系统后再次尝试。
