### ISSUE TITLE
文档错误，图文不一致

### ISSUE THREAD

**Issue by hf-xz** [nakanomikuorg/arch-guide#163]
https://arch.icekylin.online/guide/rookie/basic-install.html#_8-挂载
代码第4、5行：

```zsh
mkdir -p /mnt/boot # 创建 /boot 目录
mount /dev/sdxn /mnt/boot # 挂载 /boot 目录
```

图中给的路径是 `/mnt/boot/efi`，经查询应该是图中的路径（应该是？我第一次装），望修改一下代码部分，避免新人糊涂。

**Comment by wuhang2003** [comment]
见 #135 （

**Comment by hf-xz** [comment]
@wuhang2003 我等下在公司电脑再装一次，可以做截图，截图有什么要求吗？

**Comment by wuhang2003** [comment]
> @wuhang2003 我等下在公司电脑再装一次，可以做截图，截图有什么要求吗？

参考 https://github.com/nakanomikuorg/arch-guide/commit/054e190187d6edc7697be67359848a453cd7c8b2

尺寸应该可以不做要求

**Comment by ice-kylin** [comment]
截图清晰可见即可，最好转成 webp 格式，避免网络请求压力过大

**Comment by hf-xz** [comment]
1920x1080 + webp，等下装完了发pr
