### ISSUE TITLE
关于游戏娱乐的建议

### ISSUE THREAD

**Issue by s-chance** [nakanomikuorg/arch-guide#169]
一个专门的linux game网站[Gamux](https://www.linuxgame.cn/)，github上有相应的组织[Gamuxorg](https://github.com/Gamuxorg)及其[bbs论坛](https://github.com/Gamuxorg/bbs)。
不过，其软件是以各种网盘的形式进行分享，软件包以AppImage格式为主。

**Comment by jinzhongjia** [comment]
这个网站的游戏基本均是steam上售卖的游戏，换言之就是盗版游戏
而且采取appimage的方式就代表着每次打包均要完整包含一遍运行环境（占用空间，而且这种方案看起来似乎无法打mod），如果是玩游戏，steam基本足够，使用proton即可
