### ISSUE TITLE
输入法和网络代理相关内容过时 / 待补充

### ISSUE THREAD

**Issue by w568w** [nakanomikuorg/arch-guide#185]
1. 根据最近更新的 [Using Fcitx 5 on Wayland](https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland) 一节，当安装 KDE Plasma (with Wayland) 时，应当：
  - **绝不全局设置 `GTK_IM_MODULE`, `QT_IM_MODULE`, `SDL_IM_MODULE`**，除非个别使用 GTK2、Glib 的应用出现问题（则单独为他们设置）；
  - 仅设置 `XMODIFIERS=@im=fcitx`；
  - **在「系统设置 - 输入设备 - 虚拟键盘」中选中 Fcitx 5**；
  - **在 Electron 和 Chromium 应用程序中加入 `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime` 启动参数**。
  
而目前指南「桌面环境与常用应用安装」一节仍不分情况地建议写入：

```
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus
```

建议添加关于 Wayland 的说明，否则可能遭遇[一些问题](https://fcitx-im.org/wiki/Special:MyLanguage/FAQ#Candidate_window_is_blinking_under_wayland_with_Fcitx_5)。

2. 目前 Clash 内核及其相关客户端均已停止维护，建议在「archlinux 透明代理」一节中添加说明，或干脆丢弃对 Clash 的介绍。

**Comment by wuhang2003** [comment]
完全丢 Clash 不大可能，现阶段先加提醒吧（
目前已经看到 Clash 系项目（Meta，Verge）有接班了，但目前看着还比较新还没 aur
