### ISSUE TITLE
忘记创建efi分区，以为它是/boot分区，是不是得重新来过？

### ISSUE THREAD

**Issue by ufofly** [nakanomikuorg/arch-guide#189]
第7步的时候，因为是虚拟机全新安装，没有创建efi分区，是不是得重新来过？重回根目录好像也无法对btrfs进行分区了
![image](https://github.com/nakanomikuorg/arch-guide/assets/8202950/1f859cae-784e-4391-9b7e-162ffaf6eb45)
![image](https://github.com/nakanomikuorg/arch-guide/assets/8202950/7c102e6c-6e33-4f27-a4ba-3a4120ff940a)
![image](https://github.com/nakanomikuorg/arch-guide/assets/8202950/6a527a0b-c0c9-42d4-8e2c-4d370cacb9d9)

**Comment by wuhang2003** [comment]
那可能确实需要重新分区了（
毕竟没 EFI 分区无法写引导

**Comment by ufofly** [comment]
> 那可能确实需要重新分区了（ 毕竟没 EFI 分区无法写引导

发现虚拟机不是efi引导，只能通过efi引导安装吗？bios不行吗？

**Comment by wuhang2003** [comment]
用 BIOS 引导那你可能也得分（
![image](https://github.com/nakanomikuorg/arch-guide/assets/108316419/4f755a51-e828-49d8-891e-86fc328fc65f)

https://wiki.archlinuxcn.org/wiki/GRUB#GUID_%E5%88%86%E5%8C%BA%E8%A1%A8_(GPT)_%E7%89%B9%E6%AE%8A%E6%93%8D%E4%BD%9C

**Comment by ufofly** [comment]
重来一遍起飞
![image](https://github.com/nakanomikuorg/arch-guide/assets/8202950/6bc5c812-b73d-414c-86e3-e9c9d143c68f)

**Comment by ufofly** [comment]
![111](https://github.com/nakanomikuorg/arch-guide/assets/8202950/58aacd4b-8758-4d4d-a9fc-f38ee36a108c)
还是Arch社区的文档比较适合新手，arch牛逼
