### ISSUE TITLE
文档格式优化: 关于 fcitx5-nord 链接不一致问题

### ISSUE THREAD

**Issue by s-chance** [nakanomikuorg/arch-guide#199]
这里标题显示的链接与命令行的链接不一致，两个链接都能正常使用。

![image](https://github.com/nakanomikuorg/arch-guide/assets/91258620/5063bd04-ba8a-41e1-829d-266199974b25)

[原文链接](https://arch.icekylin.online/guide/advanced/beauty-2.html#_2-%E6%9B%B4%E6%94%B9-fcitx5-%E8%BE%93%E5%85%A5%E6%B3%95%E7%9A%AE%E8%82%A4)

**Comment by wuhang2003** [comment]
两个链接内容实际文件一致，无变更（
估计翻 fork 看到怎么安装把原仓库链接写进去了
