### ISSUE TITLE
Add i3wm/sway guide?

### ISSUE THREAD

**Issue by fioncat** [nakanomikuorg/arch-guide#205]
发现目前简中互联网上面关于i3wm/sway的教程很少，而用i3wm/sway的基本都是用arch的（

是否考虑额外增加一个i3wm/sway的安装教程？可以跟kde并行或独立安装，如果考虑我可以把我最近折腾的内容加上来

**Comment by wuhang2003** [comment]
虽然不是项目作者，但我觉得行（
或者搞大点，整点 WM 入门（i3wm sway hyprland 啥的都能写）？

**Comment by s-chance** [comment]
我之前在discussions里面稍微提过这个，不过貌似dicussions没有什么人关注？

由于个人使用的设备是比较少见的分辨率，很多配置无法适配该分辨率，遂不折腾此类环境，不太清楚广大用户对 wm 的使用需求。

另外考虑到 wm 需要使用各种第三方组件，如何引导用户选择最适合自己的方案也是一个问题，否则只是单纯出于好奇地将配置复制一份，在感到无所适从的情况下又放弃使用 wm ？个人认为 wm 的使用是一个慢慢磨合的过程，如何找到最适合每个用户自身习惯的配置也是一个需要时间的过程。

由于 wm 的自由度，对于“简明教程”来说可能不是那么的简单，不过可以尝试提交 pr，或者可以自己创建一个文档站，以文档站链接形式提交到 pr 中，以供那些愿意从桌面环境切换到 wm 的用户参考学习。个人比较倾向于后者的形式，这样可以单独围绕 wm 展开说明，而不必局限于 archlinux 发行版的简明教程中。

**Comment by fioncat** [comment]
> 我之前在discussions里面稍微提过这个，不过貌似dicussions没有什么人关注？
> 
> 由于个人使用的设备是比较少见的分辨率，很多配置无法适配该分辨率，遂不折腾此类环境，不太清楚广大用户对 wm 的使用需求。
> 
> 另外考虑到 wm 需要使用各种第三方组件，如何引导用户选择最适合自己的方案也是一个问题，否则只是单纯出于好奇地将配置复制一份，在感到无所适从的情况下又放弃使用 wm ？个人认为 wm 的使用是一个慢慢磨合的过程，如何找到最适合每个用户自身习惯的配置也是一个需要时间的过程。
> 
> 由于 wm 的自由度，对于“简明教程”来说可能不是那么的简单，不过可以尝试提交 pr，或者可以自己创建一个文档站，以文档站链接形式提交到 pr 中，以供那些愿意从桌面环境切换到 wm 的用户参考学习。个人比较倾向于后者的形式，这样可以单独围绕 wm 展开说明，而不必局限于 archlinux 发行版的简明教程中。

感谢回复。

最近仔细折腾了一下hyprland，确实太深了而且个性化很强，不适合简明教程的范畴。新手或许还是用开箱即用的DE舒服些。
