### ISSUE TITLE
light主题下很多命令的颜色不容易看清

### ISSUE THREAD

**Issue by heheda123123** [nakanomikuorg/arch-guide#216]
![image](https://github.com/nakanomikuorg/arch-guide/assets/97490782/6135d41c-6b1a-4828-83e0-0562062e0b4a)
如图，只有选中才看得清文字内容
![image](https://github.com/nakanomikuorg/arch-guide/assets/97490782/2c816574-9f00-4f39-9512-fc7b347dbe15)

**Comment by Hanserwei** [comment]
是的我也觉得，所以建议切换night模式查看。

**Comment by xuanplus** [comment]
有一说一，确实
