### ISSUE TITLE
《基础安装》章节中的命令似乎有错误

### ISSUE THREAD

**Issue by chemicalfiber** [NakanoMikuOrg/arch-guide#27]
在[archlinux基础安装#9.安装系统](https://arch.icekylin.online/rookie/basic-install.html#_9-%E5%AE%89%E8%A3%85%E7%B3%BB%E7%BB%9F)中的命令似乎有错误，其中：
```sh
pacstrap /mnt dhcpcd iwd vim sudo zsh zsh-completion
```
的`zsh-completion`应为`zsh-completions`。

在pacman中并没有找到名为不带`s`的`zsh-completion`包。

**Comment by ice-kylin** [comment]
已修改，谢谢反馈！q(≧▽≦q)
