### ISSUE TITLE
可能的翻译错误

### ISSUE THREAD

**Issue by FurryRbl** [NakanoMikuOrg/arch-guide#49]
文档位置：https://arch.icekylin.online/apps/daily.html#%F0%9F%93%96-pdf-%E4%BB%A5%E5%8F%8A%E7%94%B5%E5%AD%90%E4%B9%A6%E9%98%85%E8%AF%BB%E5%99%A8

错误内容：
![2022-06-25_07-34](https://user-images.githubusercontent.com/61524717/175747917-01dab1b4-cf3d-42dc-8f29-b55530653ee8.png)
：

正确内容：
![2022-06-25_07-35](https://user-images.githubusercontent.com/61524717/175748427-a62c2975-a638-4eb1-bc39-57868b05a11e.png)

错误原因：？plasma更新了汉化？

**Comment by ptazithos** [comment]
方便的话可以提供一张类似原图的 没有涂划的截图吗?
我可以更新进去

**Comment by FurryRbl** [comment]
> 方便的话可以提供一张类似原图的 没有涂划的截图吗? 我可以更新进去

抱歉我无法提供原图，我的设备目前不支持安装Arch，我之前的Arch已经卸载

**Comment by ptazithos** [comment]
那等候一位有缘人吧.(我不想装KDE)
