### ISSUE TITLE
建议在基础安装中生成fstab后，将 subvolid=xxx 参数删除

### ISSUE THREAD

**Issue by lituo666** [nakanomikuorg/arch-guide#56]
添加编辑文件这一步也不复杂，如果不改的话就是给小白留了个坑。虽然后面有解决方法。

**Comment by ptazithos** [comment]
确实这个地方有一些问题. 生成出来的配置文件实际上是 subvolid 和 subvol双重指定.
Timeshift恢复后subvolid会发生变化导致挂载失败. #45

**Comment by sofpixaol** [comment]
今天刚被这个坑了

**Comment by lxl66566** [comment]
我昨天也被坑了,,
