### ISSUE TITLE
NetworkManager 开启时需要关闭dhcpcd的systemd服务

### ISSUE THREAD

**Issue by Ziqi-Yang** [NakanoMikuOrg/arch-guide#75]
请参考[NetworkManager#DHCP_client](https://wiki.archlinux.org/title/NetworkManager#DHCP_client) 这一小节。在桌面环境安装的文章内只关闭连`iwd`服务，却没有关闭`dhcpcd`服务。    
不关闭dhcpcd的systemd服务平时基本没什么影响，但对于校园网之类需要认证的公共网络可能会有影响。（个人就是在没关闭前能连上校园网，但进不了登陆页面也没网）   
如果开启`dhcpcd`的`systemd`服务，就可能对nm服务造成影响。进而连不上需要认证的公共网络(能连上，但没网)。

**Comment by tksmly** [comment]
> 请参考[NetworkManager#DHCP_client](https://wiki.archlinux.org/title/NetworkManager#DHCP_client) 这一小节。在桌面环境安装的文章内只关闭连`iwd`服务，却没有关闭`dhcpcd`服务。 不关闭dhcpcd的systemd服务平时基本没什么影响，但对于校园网之类需要认证的公共网络可能会有影响。（个人就是在没关闭前能连上校园网，但进不了登陆页面也没网） 如果开启`dhcpcd`的`systemd`服务，就可能对nm服务造成影响。进而连不上需要认证的公共网络(能连上，但没网)。

事实上,并非平时基本没什么影响,首先删除网络连接,或者网络连接不是默认配置,那么会自动重新生成网络连接,但是没有ipv6
其次,NetworkManager的内存占用会大涨,但是这正常使用看不出来,能看出来的是会导致NetworkManager无法判断网络是否连通
无论如何设置都没用
