### ISSUE TITLE
使用 pacstrap 脚本安装基础包应该包括 btrfs-progs

### ISSUE THREAD

**Issue by ShenHongFei** [nakanomikuorg/arch-guide#87]
通过如下命令使用 pacstrap 脚本安装基础包：
pacstrap /mnt base base-devel linux linux-firmware
应该改成
pacstrap /mnt base base-devel linux linux-firmware btrfs-progs

否则 btrfs 不能使用吧？

**Comment by yzx9** [comment]
This should have been closed.

https://github.com/nakanomikuorg/arch-guide/blob/aad68bd592a0b200e542771ea8ed665bd8a687ba/docs/guide/rookie/basic-install.md?plain=1#L547-L550

**Comment by ShenHongFei** [comment]
好的
